#!/bin/bash





display_menu() {
    echo -e "\n\n"
    echo "-------------------- Musgravite --------------------"
    echo -e "\n"
    echo "1) Use musgravite with C"
    echo "2) Use musgravite with C++"
    echo "3) Use musgravite with D"
    echo "4) Use musgravite with Nim"
    echo "0) Exit"
    echo -e "\n"
    echo "----------------------------------------------------"
    echo -e "\n\n"
}



createWorkSpace() {
    mkdir -p ../_libs/musgravite
    mkdir -p ../_tests/
}



removeMusgraviteRepo() {
    echo "The installation was successful."
    echo "Do you want to remove the official musgravite repository from your workflow? [Y / N]"

    read -p "Enter the option number: " option

    if $option == 'Y':
        cd .. && rm -r Musgravite
    fi
}



musgraviteC() {
    createWorkSpace


    if [ -f ./musgravite/'C Wrapper' ]; then
        mv ./musgravite/'C Wrapper'/* ../_libs/musgravite/
    else
        echo "Error: Directory 'C Wrapper' not found."
        return 1
    fi

    if [ -f ./musgravite/musgravite.hpp ]; then
        mv ./musgravite/musgravite.hpp ../_libs/musgravite
    else
        echo "Error: File 'musgravite.hpp' not found."
        return 1
    fi


    removeMusgraviteRepo
}



musgraviteCpp() {
    createWorkSpace


    if [ -f ./musgravite/musgravite.hpp ]; then
        mv ./musgravite/musgravite.hpp ../_libs/musgravite
    else
        echo "Error: File 'musgravite.hpp' not found."
        return 1
    fi

    removeMusgraviteRepo
}





if [ "$1" == "-c" ]; then
    musgraviteC
    exit 0
elif [ "$1" == "-cpp" ]; then
    musgraviteCpp
    exit 0
fi





while true; do
    display_menu

    read -p "Enter the option number: " option

    case $option in
        1) musgraviteC ;;
        2) musgraviteCpp ;;
        0) echo "Exiting..."; exit 0 ;;
        *) echo "Invalid option. Please try again." ;;
    esac
done