#!/bin/bash





display_menu() {
    echo -e "\n\n"
    echo "-------------------- Musgravite --------------------"
    echo -e "\n"
    echo "1) Use musgravite with C"
    echo "2) Use musgravite with C++"
    echo "3) Use musgravite with D"
    echo "4) Use musgravite with Nim"
    echo -e "\n"
    echo "----------------------------------------------------"
    echo -e "\n\n"
}





while true; do
    display_menu
done